# Generated by Django 5.1.1 on 2024-10-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient_quantity',
            field=models.FloatField(default=1),
        ),
    ]
