# Generated by Django 5.1.1 on 2024-10-10 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal', '0003_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
