# Generated by Django 5.1.1 on 2024-10-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcal', '0004_alter_userlog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealquantity',
            name='day',
        ),
        migrations.RemoveField(
            model_name='mealquantity',
            name='meal',
        ),
        migrations.DeleteModel(
            name='DailyConsumption',
        ),
        migrations.DeleteModel(
            name='MealQuantity',
        ),
    ]
